# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 371)
        self.choose_button = QtWidgets.QPushButton(Form)
        self.choose_button.setGeometry(QtCore.QRect(30, 320, 81, 31))
        self.choose_button.setObjectName("choose_button")
        self.create_button = QtWidgets.QPushButton(Form)
        self.create_button.setGeometry(QtCore.QRect(130, 320, 91, 31))
        self.create_button.setObjectName("create_button")
        self.profiles_table = QtWidgets.QListWidget(Form)
        self.profiles_table.setGeometry(QtCore.QRect(20, 20, 421, 281))
        self.profiles_table.setObjectName("profiles_table")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setGeometry(QtCore.QRect(350, 320, 81, 31))
        self.delete_button.setObjectName("delete_button")
        self.rename_button = QtWidgets.QPushButton(Form)
        self.rename_button.setGeometry(QtCore.QRect(240, 320, 91, 31))
        self.rename_button.setObjectName("rename_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Профили пользователей"))
        self.choose_button.setText(_translate("Form", "Выбрать"))
        self.create_button.setText(_translate("Form", "Создать новый"))
        self.delete_button.setText(_translate("Form", "Удалить"))
        self.rename_button.setText(_translate("Form", "Переименовать"))
